import { readFileSync } from "fs";
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import jsonc from "eslint-plugin-jsonc";
import jsoncParser from "jsonc-eslint-parser";
import pluginPrettier from "eslint-plugin-prettier";
import eslintConfigPrettier from "eslint-config-prettier";
import { defineConfig } from "eslint/config";

const prettierConfig = JSON.parse(
    readFileSync(new URL("./.prettierrc", import.meta.url))
);

export default defineConfig([
    {
        // Generated by openapi-codegen; sppComponents.ts/sppSchemas.ts get
        // overwritten on every regeneration, so lint fixes here don't stick.
        ignores: ["src/api/generated/**"],
    },

    {
        files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
        plugins: { js, prettier: pluginPrettier },
        extends: ["js/recommended"],
        rules: {
            "prettier/prettier": ["error", prettierConfig], // Runs prettier as eslint rule
        },
        languageOptions: { globals: globals.browser },
    },

    tseslint.configs.recommended,
    pluginReact.configs.flat.recommended,
    pluginReact.configs.flat["jsx-runtime"], // No need to import React for JSX (automatic runtime)
    {
        settings: { react: { version: "detect" } },
        rules: {
            "react/prop-types": "off", // TypeScript already checks prop types
        },
    },
    eslintConfigPrettier, // Disables eslint rules conflicting with prettier

    {
        files: ["**/*.{json,jsonc}"],
        plugins: { jsonc },
        languageOptions: {
            parser: jsoncParser,
        },
        rules: {
            "jsonc/no-comments": "off",
            "jsonc/array-bracket-spacing": ["error", "never"],
            "jsonc/object-curly-spacing": ["error", "always"],
        },
    },
]);
