/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all events */
        get: operations["EventsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all maps */
        get: operations["MapsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get map by id */
        get: operations["MapsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedMetaDocumented: {
            /** Number of items per page */
            itemsPerPage: number;
            /** Total number of items */
            totalItems: number;
            /** Current requested page */
            currentPage: number;
            /** Total number of pages */
            totalPages: number;
            /** Sorting by columns */
            sortBy?: (string | ("ASC" | "DESC"))[][];
            /** Search by fields */
            searchBy?: string[];
            /** Search term */
            search?: string;
            /** List of selected fields */
            select?: string[];
            /** Filters that applied to the query */
            filter?: Record<string, never>;
        };
        PaginatedLinksDocumented: {
            /** Link to first page */
            first?: string;
            /** Link to previous page */
            previous?: string;
            /** Link to current page */
            current?: string;
            /** Link to next page */
            next?: string;
            /** Link to last page */
            last?: string;
        };
        PaginatedDocumented: {
            /** Array of entities */
            data: Record<string, never>[];
            /** Pagination Metadata */
            meta: components["schemas"]["PaginatedMetaDocumented"];
            /** Links to pages */
            links: components["schemas"]["PaginatedLinksDocumented"];
        };
        FindAllEventsDto: {
            /** @description Event ID */
            id: number;
            /** @description Event type */
            type: number;
            /** @description Medal awarded for the event */
            medal: number | null;
            /** @description Event date as a unix timestamp in milliseconds */
            eventDate: number | null;
            /** @description Map ID */
            mapId: number | null;
            /** @description User ID */
            userId: number | null;
            /** @description Map name */
            mapname: string | null;
            /** @description Username */
            username: string | null;
        };
        MapCreatorDto: {
            /** @description User ID */
            id: number;
            /** @description Username */
            username: string;
        };
        FindAllMapsDto: {
            /** @description Map ID */
            id: number;
            /** @description Map name */
            mapname: string | null;
            /** @description Map date as a unix timestamp */
            date: number | null;
            /** @description Anticoop count */
            anticoop: number | null;
            /** @description Jets count */
            jets: number | null;
            /** @description M79 count */
            m79: number | null;
            /** @description Grenade count */
            nade: number | null;
            /** @description Switch count */
            switch: number | null;
            /** @description Coop count */
            coop: number | null;
            /** @description M79 coop count */
            m79c: number | null;
            /** @description Difficulty rank among all maps */
            hardest: number | null;
            /** @description Map creators */
            creators: components["schemas"]["MapCreatorDto"][];
            /** @description Number of recorded runs on this map */
            recordsCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    EventsController_findAll: {
        parameters: {
            query?: {
                /**
                 * @description Page number to retrieve. If you provide invalid value the default page number will applied
                 *
                 *     **Example:** 1
                 *
                 *
                 *     **Default Value:** 1
                 */
                page?: number;
                /**
                 * @description Number of records per page.
                 *
                 *
                 *     **Example:** 20
                 *
                 *
                 *
                 *     **Default Value:** 20
                 *
                 *
                 *
                 *     **Max Value:** 100
                 *
                 *
                 *     If provided value is greater than max value, max value will be applied.
                 */
                limit?: number;
                /**
                 * @description Filter by type query param.
                 *
                 *     **Format:** filter.type={$not}:OPERATION:VALUE
                 *
                 *
                 *
                 *     **Example:** filter.type=$btw:John Doe&filter.type=$contains:John Doe
                 *
                 *     **Available Operations**
                 *     - $eq
                 *
                 *     - $gt
                 *
                 *     - $gte
                 *
                 *     - $in
                 *
                 *     - $null
                 *
                 *     - $lt
                 *
                 *     - $lte
                 *
                 *     - $btw
                 *
                 *     - $ilike
                 *
                 *     - $sw
                 *
                 *     - $contains
                 *
                 *     - $not
                 *
                 *     - $and
                 *
                 *     - $or
                 */
                "filter.type"?: string[];
                /**
                 * @description Filter by medal query param.
                 *
                 *     **Format:** filter.medal={$not}:OPERATION:VALUE
                 *
                 *
                 *
                 *     **Example:** filter.medal=$btw:John Doe&filter.medal=$contains:John Doe
                 *
                 *     **Available Operations**
                 *     - $eq
                 *
                 *     - $gt
                 *
                 *     - $gte
                 *
                 *     - $in
                 *
                 *     - $null
                 *
                 *     - $lt
                 *
                 *     - $lte
                 *
                 *     - $btw
                 *
                 *     - $ilike
                 *
                 *     - $sw
                 *
                 *     - $contains
                 *
                 *     - $not
                 *
                 *     - $and
                 *
                 *     - $or
                 */
                "filter.medal"?: string[];
                /**
                 * @description Filter by eventDate query param.
                 *
                 *     **Format:** filter.eventDate={$not}:OPERATION:VALUE
                 *
                 *
                 *
                 *     **Example:** filter.eventDate=$btw:John Doe&filter.eventDate=$contains:John Doe
                 *
                 *     **Available Operations**
                 *     - $eq
                 *
                 *     - $gt
                 *
                 *     - $gte
                 *
                 *     - $in
                 *
                 *     - $null
                 *
                 *     - $lt
                 *
                 *     - $lte
                 *
                 *     - $btw
                 *
                 *     - $ilike
                 *
                 *     - $sw
                 *
                 *     - $contains
                 *
                 *     - $not
                 *
                 *     - $and
                 *
                 *     - $or
                 */
                "filter.eventDate"?: string[];
                /**
                 * @description Parameter to sort by.
                 *     To sort by multiple fields, just provide query param multiple types. The order in url defines an order of sorting
                 *
                 *     **Format:** {fieldName}:{DIRECTION}
                 *
                 *
                 *     **Example:** sortBy=id:DESC&sortBy=type:DESC
                 *
                 *
                 *     **Default Value:** id:ASC
                 *
                 *     **Available Fields**
                 *     - id
                 *
                 *     - type
                 *
                 *     - medal
                 *
                 *     - eventDate
                 */
                sortBy?: ("id:ASC" | "id:DESC" | "type:ASC" | "type:DESC" | "medal:ASC" | "medal:DESC" | "eventDate:ASC" | "eventDate:DESC")[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumented"] & {
                        data?: components["schemas"]["FindAllEventsDto"][];
                        meta?: {
                            select?: string[];
                            filter?: {
                                type?: string | string[];
                                medal?: string | string[];
                                eventDate?: string | string[];
                            };
                        };
                    };
                };
            };
        };
    };
    MapsController_findAll: {
        parameters: {
            query?: {
                /**
                 * @description Page number to retrieve. If you provide invalid value the default page number will applied
                 *
                 *     **Example:** 1
                 *
                 *
                 *     **Default Value:** 1
                 */
                page?: number;
                /**
                 * @description Number of records per page.
                 *
                 *
                 *     **Example:** 20
                 *
                 *
                 *
                 *     **Default Value:** 20
                 *
                 *
                 *
                 *     **Max Value:** 100
                 *
                 *
                 *     If provided value is greater than max value, max value will be applied.
                 */
                limit?: number;
                /**
                 * @description Filter by mapname query param.
                 *
                 *     **Format:** filter.mapname={$not}:OPERATION:VALUE
                 *
                 *
                 *
                 *     **Example:** filter.mapname=$btw:John Doe&filter.mapname=$contains:John Doe
                 *
                 *     **Available Operations**
                 *     - $eq
                 *
                 *     - $gt
                 *
                 *     - $gte
                 *
                 *     - $in
                 *
                 *     - $null
                 *
                 *     - $lt
                 *
                 *     - $lte
                 *
                 *     - $btw
                 *
                 *     - $ilike
                 *
                 *     - $sw
                 *
                 *     - $contains
                 *
                 *     - $not
                 *
                 *     - $and
                 *
                 *     - $or
                 */
                "filter.mapname"?: string[];
                /**
                 * @description Filter by date query param.
                 *
                 *     **Format:** filter.date={$not}:OPERATION:VALUE
                 *
                 *
                 *
                 *     **Example:** filter.date=$btw:John Doe&filter.date=$contains:John Doe
                 *
                 *     **Available Operations**
                 *     - $eq
                 *
                 *     - $gt
                 *
                 *     - $gte
                 *
                 *     - $in
                 *
                 *     - $null
                 *
                 *     - $lt
                 *
                 *     - $lte
                 *
                 *     - $btw
                 *
                 *     - $ilike
                 *
                 *     - $sw
                 *
                 *     - $contains
                 *
                 *     - $not
                 *
                 *     - $and
                 *
                 *     - $or
                 */
                "filter.date"?: string[];
                /**
                 * @description Parameter to sort by.
                 *     To sort by multiple fields, just provide query param multiple types. The order in url defines an order of sorting
                 *
                 *     **Format:** {fieldName}:{DIRECTION}
                 *
                 *
                 *     **Example:** sortBy=id:DESC&sortBy=mapname:DESC
                 *
                 *
                 *     **Default Value:** id:ASC
                 *
                 *     **Available Fields**
                 *     - id
                 *
                 *     - mapname
                 *
                 *     - date
                 *
                 *     - hardest
                 */
                sortBy?: ("id:ASC" | "id:DESC" | "mapname:ASC" | "mapname:DESC" | "date:ASC" | "date:DESC" | "hardest:ASC" | "hardest:DESC")[];
                /**
                 * @description Search term to filter result values
                 *
                 *     **Example:** John
                 *
                 *
                 *     **Default Value:** No default value
                 */
                search?: string;
                /**
                 * @description List of fields to search by term to filter result values
                 *
                 *     **Example:** mapname
                 *
                 *
                 *     **Default Value:** By default all fields mentioned below will be used to search by term
                 *
                 *     **Available Fields**
                 *     - mapname
                 */
                searchBy?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumented"] & {
                        data?: components["schemas"]["FindAllMapsDto"][];
                        meta?: {
                            select?: string[];
                            filter?: {
                                mapname?: string | string[];
                                date?: string | string[];
                            };
                        };
                    };
                };
            };
        };
    };
    MapsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllMapsDto"];
                };
            };
        };
    };
}
