import avatarImg from "@/assets/avatars/avatar.png";

// Temporary data for testing tables
export interface User {
    rank: number;
    username: string;
    avatar: string;
    country: string;
    passed: number;
    records: number;
    hardest: number;
    gold: number;
    silver: number;
    bronze: number;
}

export const usersData: User[] = [
    {
        rank: 1,
        username: "Account4",
        avatar: avatarImg,
        country: "PL",
        passed: 92,
        records: 500,
        hardest: 10,
        gold: 50,
        silver: 320,
        bronze: 210,
    },
    {
        rank: 2,
        username: "Account12",
        avatar: avatarImg,
        country: "GB",
        passed: 81,
        records: 1280,
        hardest: 65,
        gold: 60,
        silver: 470,
        bronze: 390,
    },
    {
        rank: 3,
        username: "Account14",
        avatar: avatarImg,
        country: "US",
        passed: 74,
        records: 1750,
        hardest: 50,
        gold: 20,
        silver: 300,
        bronze: 250,
    },
    {
        rank: 4,
        username: "Account7",
        avatar: avatarImg,
        country: "DE",
        passed: 88,
        records: 2200,
        hardest: 70,
        gold: 720,
        silver: 510,
        bronze: 430,
    },
    {
        rank: 5,
        username: "Account9",
        avatar: avatarImg,
        country: "FR",
        passed: 95,
        records: 150,
        hardest: 85,
        gold: 890,
        silver: 610,
        bronze: 470,
    },
    {
        rank: 6,
        username: "Account11",
        avatar: avatarImg,
        country: "IT",
        passed: 68,
        records: 1500,
        hardest: 42,
        gold: 360,
        silver: 280,
        bronze: 190,
    },
    {
        rank: 7,
        username: "Account15",
        avatar: avatarImg,
        country: "ES",
        passed: 77,
        records: 2000,
        hardest: 55,
        gold: 510,
        silver: 400,
        bronze: 320,
    },
    {
        rank: 8,
        username: "Account18",
        avatar: avatarImg,
        country: "JP",
        passed: 83,
        records: 2300,
        hardest: 66,
        gold: 630,
        silver: 470,
        bronze: 350,
    },
    {
        rank: 9,
        username: "Account21",
        avatar: avatarImg,
        country: "CN",
        passed: 72,
        records: 160,
        hardest: 48,
        gold: 100,
        silver: 290,
        bronze: 210,
    },
    {
        rank: 10,
        username: "Account23",
        avatar: avatarImg,
        country: "RU",
        passed: 85,
        records: 1200,
        hardest: 72,
        gold: 710,
        silver: 500,
        bronze: 410,
    },
    {
        rank: 11,
        username: "Account26",
        avatar: avatarImg,
        country: "CA",
        passed: 79,
        records: 1900,
        hardest: 60,
        gold: 580,
        silver: 420,
        bronze: 330,
    },
    {
        rank: 12,
        username: "Account28",
        avatar: avatarImg,
        country: "AU",
        passed: 88,
        records: 2350,
        hardest: 75,
        gold: 720,
        silver: 510,
        bronze: 440,
    },
    {
        rank: 13,
        username: "Account30",
        avatar: avatarImg,
        country: "BR",
        passed: 65,
        records: 1300,
        hardest: 38,
        gold: 320,
        silver: 250,
        bronze: 180,
    },
    {
        rank: 14,
        username: "Account32",
        avatar: avatarImg,
        country: "SE",
        passed: 82,
        records: 2150,
        hardest: 68,
        gold: 650,
        silver: 480,
        bronze: 370,
    },
    {
        rank: 15,
        username: "Account34",
        avatar: avatarImg,
        country: "NL",
        passed: 90,
        records: 2700,
        hardest: 80,
        gold: 830,
        silver: 590,
        bronze: 460,
    },
    {
        rank: 16,
        username: "Account36",
        avatar: avatarImg,
        country: "PL",
        passed: 71,
        records: 1550,
        hardest: 45,
        gold: 410,
        silver: 300,
        bronze: 220,
    },
    {
        rank: 17,
        username: "Account38",
        avatar: avatarImg,
        country: "GB",
        passed: 78,
        records: 2050,
        hardest: 58,
        gold: 560,
        silver: 430,
        bronze: 340,
    },
    {
        rank: 18,
        username: "Account40",
        avatar: avatarImg,
        country: "US",
        passed: 86,
        records: 2450,
        hardest: 72,
        gold: 710,
        silver: 500,
        bronze: 410,
    },
    {
        rank: 19,
        username: "Account42",
        avatar: avatarImg,
        country: "DE",
        passed: 69,
        records: 1600,
        hardest: 48,
        gold: 420,
        silver: 310,
        bronze: 240,
    },
    {
        rank: 20,
        username: "Account44",
        avatar: avatarImg,
        country: "FR",
        passed: 84,
        records: 2300,
        hardest: 70,
        gold: 680,
        silver: 490,
        bronze: 390,
    },
    {
        rank: 21,
        username: "Account45",
        avatar: avatarImg,
        country: "IT",
        passed: 76,
        records: 2000,
        hardest: 55,
        gold: 520,
        silver: 410,
        bronze: 330,
    },
    {
        rank: 22,
        username: "Account46",
        avatar: avatarImg,
        country: "ES",
        passed: 81,
        records: 2100,
        hardest: 62,
        gold: 600,
        silver: 450,
        bronze: 360,
    },
    {
        rank: 23,
        username: "Account48",
        avatar: avatarImg,
        country: "JP",
        passed: 74,
        records: 1800,
        hardest: 52,
        gold: 470,
        silver: 380,
        bronze: 290,
    },
    {
        rank: 24,
        username: "Account50",
        avatar: avatarImg,
        country: "CN",
        passed: 89,
        records: 2500,
        hardest: 78,
        gold: 760,
        silver: 540,
        bronze: 420,
    },
    {
        rank: 25,
        username: "Account52",
        avatar: avatarImg,
        country: "RU",
        passed: 66,
        records: 1500,
        hardest: 42,
        gold: 380,
        silver: 300,
        bronze: 230,
    },
    {
        rank: 26,
        username: "Account54",
        avatar: avatarImg,
        country: "CA",
        passed: 77,
        records: 1950,
        hardest: 57,
        gold: 540,
        silver: 430,
        bronze: 340,
    },
    {
        rank: 27,
        username: "Account56",
        avatar: avatarImg,
        country: "AU",
        passed: 85,
        records: 2350,
        hardest: 70,
        gold: 710,
        silver: 500,
        bronze: 410,
    },
    {
        rank: 28,
        username: "Account58",
        avatar: avatarImg,
        country: "BR",
        passed: 70,
        records: 1600,
        hardest: 46,
        gold: 430,
        silver: 320,
        bronze: 240,
    },
    {
        rank: 29,
        username: "Account60",
        avatar: avatarImg,
        country: "SE",
        passed: 83,
        records: 2200,
        hardest: 66,
        gold: 650,
        silver: 480,
        bronze: 370,
    },
    {
        rank: 30,
        username: "Account62",
        avatar: avatarImg,
        country: "NL",
        passed: 91,
        records: 2750,
        hardest: 82,
        gold: 870,
        silver: 620,
        bronze: 470,
    },
];
